"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const create_1 = require("../controller/products/create");
const delete_1 = require("../controller/products/delete");
const getAll_1 = require("../controller/products/getAll");
const getFor_1 = require("../controller/products/getFor");
const getOne_1 = require("../controller/products/getOne");
const update_1 = require("../controller/products/update");
const authentication_1 = require("../middlewares/authentication");
const roles_1 = require("../middlewares/roles");
const router = (0, express_1.Router)();
router.get('/filter/:id', getFor_1.ProductsGetForController.getFor);
router.post('/', authentication_1.authenticate, roles_1.isAdmin, create_1.ProductsCreateController.create);
router.get('/:id', getOne_1.ProductsGetByIdController.getOneById);
router.patch('/:id', authentication_1.authenticate, roles_1.isAdmin, update_1.ProductsUpdateController.update);
router.delete('/:id', authentication_1.authenticate, roles_1.isAdmin, delete_1.ProductsDeleteController.delete);
router.get('/', getAll_1.GetAllProductsController.getAll);
router.get('/getbyname', getOne_1.ProductsGetByIdController.getByName);
exports.default = router;
